import { AlumniProfile } from '@/types/alumni';

export const MOCK_ALUMNI: AlumniProfile[] = [
  {
    id: 1,
    fullName: 'Ahmad Rizki Pratama',
    email: 'ahmad.rizki@example.com',
    profilePhoto: '/assets/avatars/avatar-1.png',
    nim: '1501234',
    major: 'Teknik Elektro',
    graduationYear: 2018,
    position: 'Senior Software Engineer',
    currentCompany: 'Google Indonesia',
    phoneNumber: '+62812345678',
    address: 'Jakarta, Indonesia',
    bio: 'Passionate software engineer with 5+ years of experience in full-stack development.',
    interests: ['Software Development', 'AI/ML', 'Open Source'],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
    ],
    workExperience: [
      {
        id: '1',
        company: 'Google Indonesia',
        position: 'Senior Software Engineer',
        startDate: '2020-01-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'Technology',
      },
    ],
    skills: [
      {
        id: '1',
        name: 'React',
        category: 'Frontend',
        level: 'expert',
        endorsements: 15,
        verified: true,
      },
      {
        id: '2',
        name: 'Node.js',
        category: 'Backend',
        level: 'expert',
        endorsements: 12,
        verified: true,
      },
      {
        id: '3',
        name: 'TypeScript',
        category: 'Programming',
        level: 'advanced',
        endorsements: 10,
        verified: false,
      },
    ],
    certifications: [],
    socialLinks: [],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: ['Software Development', 'Career Guidance'],
      maxMentees: 5,
      currentMentees: 2,
      preferredCommunication: ['Video Call', 'Chat'],
      seekingMentorship: false,
    },
    profileCompleteness: 85,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2023-01-01',
    profileViews: 150,
    connectionsCount: 45,
    articlesCount: 3,
    menteeCount: 2,
    role: 'user',
  },
  {
    id: 2,
    fullName: 'Sari Dewi Lestari',
    email: 'sari.dewi@example.com',
    profilePhoto: '/assets/avatars/avatar-2.png',
    nim: '1601234',
    major: 'Teknik Elektro',
    graduationYear: 2019,
    position: 'Product Manager',
    currentCompany: 'Tokopedia',
    phoneNumber: '+62812345679',
    address: 'Jakarta, Indonesia',
    bio: 'Product manager focused on user experience and data-driven decisions.',
    interests: ['Product Management', 'UX Design', 'Data Analytics'],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
    ],
    workExperience: [
      {
        id: '2',
        company: 'Tokopedia',
        position: 'Product Manager',
        startDate: '2021-03-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'E-commerce',
      },
    ],
    skills: [
      {
        id: '4',
        name: 'Product Management',
        category: 'Business',
        level: 'expert',
        endorsements: 20,
        verified: true,
      },
      {
        id: '5',
        name: 'Data Analysis',
        category: 'Analytics',
        level: 'advanced',
        endorsements: 8,
        verified: false,
      },
    ],
    certifications: [],
    socialLinks: [],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: ['Product Management', 'Career Transition'],
      maxMentees: 3,
      currentMentees: 1,
      preferredCommunication: ['Video Call'],
      seekingMentorship: false,
    },
    profileCompleteness: 90,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2023-02-01',
    profileViews: 120,
    connectionsCount: 38,
    articlesCount: 5,
    menteeCount: 1,
    role: 'user',
  },
  {
    id: 3,
    fullName: 'Budi Santoso',
    email: 'budi.santoso@example.com',
    profilePhoto: '/assets/avatars/avatar-3.png',
    nim: '1401234',
    major: 'Teknik Elektro',
    graduationYear: 2015,
    position: 'Engineering Manager',
    currentCompany: 'Gojek',
    phoneNumber: '+62812345680',
    address: 'Jakarta, Indonesia',
    bio: 'Engineering leader with experience in scaling teams and building robust systems.',
    interests: [
      'Engineering Leadership',
      'System Architecture',
      'Team Building',
    ],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
    ],
    workExperience: [
      {
        id: '3',
        company: 'Gojek',
        position: 'Engineering Manager',
        startDate: '2019-06-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'Technology',
      },
    ],
    skills: [
      {
        id: '6',
        name: 'Leadership',
        category: 'Management',
        level: 'expert',
        endorsements: 25,
        verified: true,
      },
      {
        id: '7',
        name: 'System Architecture',
        category: 'Technical',
        level: 'expert',
        endorsements: 18,
        verified: true,
      },
    ],
    certifications: [],
    socialLinks: [],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: ['Engineering Leadership', 'Career Growth'],
      maxMentees: 4,
      currentMentees: 3,
      preferredCommunication: ['Video Call', 'In-person'],
      seekingMentorship: false,
    },
    profileCompleteness: 95,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2022-12-01',
    profileViews: 200,
    connectionsCount: 67,
    articlesCount: 8,
    menteeCount: 3,
    role: 'user',
  },
  {
    id: 4,
    fullName: 'Maya Indira Putri',
    email: 'maya.indira@example.com',
    profilePhoto: '/assets/avatars/avatar-4.png',
    nim: '1701234',
    major: 'Teknik Elektro',
    graduationYear: 2020,
    position: 'Data Scientist',
    currentCompany: 'Shopee',
    phoneNumber: '+62812345681',
    address: 'Singapore',
    bio: 'Data scientist specializing in machine learning and predictive analytics for e-commerce.',
    interests: ['Machine Learning', 'Data Science', 'AI Research'],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
      { name: 'Mandarin', level: 'intermediate' },
    ],
    workExperience: [
      {
        id: '4',
        company: 'Shopee',
        position: 'Data Scientist',
        startDate: '2021-08-01',
        isCurrent: true,
        location: 'Singapore',
        industry: 'E-commerce',
      },
    ],
    skills: [
      {
        id: '8',
        name: 'Python',
        category: 'Programming',
        level: 'expert',
        endorsements: 22,
        verified: true,
      },
      {
        id: '9',
        name: 'Machine Learning',
        category: 'AI/ML',
        level: 'expert',
        endorsements: 18,
        verified: true,
      },
      {
        id: '10',
        name: 'SQL',
        category: 'Database',
        level: 'advanced',
        endorsements: 15,
        verified: false,
      },
    ],
    certifications: [
      {
        id: '1',
        name: 'Google Cloud Professional Data Engineer',
        issuer: 'Google Cloud',
        issueDate: '2022-05-15',
        expiryDate: '2025-05-15',
        credentialId: 'GCP-PDE-789',
        credentialUrl: 'https://cloud.google.com/certification',
      },
    ],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/mayaindira',
        username: 'mayaindira',
      },
      {
        platform: 'github',
        url: 'https://github.com/mayaindira',
        username: 'mayaindira',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: ['Data Science', 'Machine Learning', 'Career in Tech'],
      maxMentees: 3,
      currentMentees: 2,
      preferredCommunication: ['Video Call', 'Chat'],
      seekingMentorship: false,
    },
    profileCompleteness: 92,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2023-03-01',
    profileViews: 180,
    connectionsCount: 52,
    articlesCount: 6,
    menteeCount: 2,
    role: 'user',
  },
  {
    id: 5,
    fullName: 'Reza Firmansyah',
    email: 'reza.firmansyah@example.com',
    profilePhoto: '/assets/avatars/avatar-5.png',
    nim: '1301234',
    major: 'Teknik Elektro',
    graduationYear: 2014,
    position: 'CTO',
    currentCompany: 'TechStart Indonesia',
    phoneNumber: '+62812345682',
    address: 'Bandung, Indonesia',
    bio: 'Technology entrepreneur and startup founder with expertise in IoT and embedded systems.',
    interests: ['IoT', 'Embedded Systems', 'Entrepreneurship', 'Startup'],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
    ],
    workExperience: [
      {
        id: '5',
        company: 'TechStart Indonesia',
        position: 'CTO & Co-Founder',
        startDate: '2018-01-01',
        isCurrent: true,
        location: 'Bandung, Indonesia',
        industry: 'Technology',
      },
    ],
    skills: [
      {
        id: '11',
        name: 'IoT Development',
        category: 'Hardware',
        level: 'expert',
        endorsements: 30,
        verified: true,
      },
      {
        id: '12',
        name: 'Embedded Systems',
        category: 'Hardware',
        level: 'expert',
        endorsements: 28,
        verified: true,
      },
      {
        id: '13',
        name: 'Startup Management',
        category: 'Business',
        level: 'advanced',
        endorsements: 20,
        verified: false,
      },
    ],
    certifications: [],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/rezafirmansyah',
        username: 'rezafirmansyah',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: [
        'Entrepreneurship',
        'IoT Development',
        'Startup Strategy',
      ],
      maxMentees: 5,
      currentMentees: 4,
      preferredCommunication: ['Video Call', 'In-person'],
      seekingMentorship: false,
    },
    profileCompleteness: 88,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2022-11-01',
    profileViews: 250,
    connectionsCount: 89,
    articlesCount: 12,
    menteeCount: 4,
    role: 'user',
  },
  {
    id: 6,
    fullName: 'Andi Kurniawan',
    email: 'andi.kurniawan@example.com',
    profilePhoto: '/assets/avatars/avatar-6.png',
    nim: '1801234',
    major: 'Teknik Elektro',
    graduationYear: 2021,
    position: 'DevOps Engineer',
    currentCompany: 'Traveloka',
    phoneNumber: '+62812345683',
    address: 'Jakarta, Indonesia',
    bio: 'DevOps engineer passionate about cloud infrastructure and automation.',
    interests: ['Cloud Computing', 'DevOps', 'Automation', 'Kubernetes'],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'intermediate' },
    ],
    workExperience: [
      {
        id: '6',
        company: 'Traveloka',
        position: 'DevOps Engineer',
        startDate: '2022-02-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'Travel Technology',
      },
    ],
    skills: [
      {
        id: '14',
        name: 'AWS',
        category: 'Cloud',
        level: 'advanced',
        endorsements: 12,
        verified: true,
      },
      {
        id: '15',
        name: 'Kubernetes',
        category: 'DevOps',
        level: 'advanced',
        endorsements: 10,
        verified: false,
      },
      {
        id: '16',
        name: 'Docker',
        category: 'DevOps',
        level: 'expert',
        endorsements: 15,
        verified: true,
      },
    ],
    certifications: [
      {
        id: '2',
        name: 'AWS Certified DevOps Engineer',
        issuer: 'Amazon Web Services',
        issueDate: '2023-01-20',
        expiryDate: '2026-01-20',
        credentialId: 'AWS-DOE-456',
        credentialUrl: 'https://aws.amazon.com/certification',
      },
    ],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/andikurniawan',
        username: 'andikurniawan',
      },
      {
        platform: 'github',
        url: 'https://github.com/andikurniawan',
        username: 'andikurniawan',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: ['DevOps', 'Cloud Computing', 'Career Development'],
      maxMentees: 2,
      currentMentees: 1,
      preferredCommunication: ['Chat', 'Video Call'],
      seekingMentorship: false,
    },
    profileCompleteness: 80,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2023-04-01',
    profileViews: 95,
    connectionsCount: 28,
    articlesCount: 2,
    menteeCount: 1,
    role: 'user',
  },
  {
    id: 7,
    fullName: 'Fitri Ramadhani',
    email: 'fitri.ramadhani@example.com',
    profilePhoto: '/assets/avatars/avatar-7.png',
    nim: '1901234',
    major: 'Teknik Elektro',
    graduationYear: 2022,
    position: 'UI/UX Designer',
    currentCompany: 'Bukalapak',
    phoneNumber: '+62812345684',
    address: 'Jakarta, Indonesia',
    bio: 'UI/UX designer with a passion for creating intuitive and beautiful user experiences.',
    interests: [
      'UI/UX Design',
      'Design Systems',
      'User Research',
      'Prototyping',
    ],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'intermediate' },
    ],
    workExperience: [
      {
        id: '7',
        company: 'Bukalapak',
        position: 'UI/UX Designer',
        startDate: '2022-07-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'E-commerce',
      },
    ],
    skills: [
      {
        id: '17',
        name: 'Figma',
        category: 'Design',
        level: 'expert',
        endorsements: 18,
        verified: true,
      },
      {
        id: '18',
        name: 'User Research',
        category: 'Design',
        level: 'advanced',
        endorsements: 12,
        verified: false,
      },
      {
        id: '19',
        name: 'Prototyping',
        category: 'Design',
        level: 'advanced',
        endorsements: 14,
        verified: true,
      },
    ],
    certifications: [],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/fitriramadhani',
        username: 'fitriramadhani',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: false,
      mentorshipAreas: [],
      maxMentees: 0,
      currentMentees: 0,
      preferredCommunication: [],
      seekingMentorship: true,
    },
    profileCompleteness: 75,
    verificationStatus: 'pending',
    accountStatus: 'active',
    joinedAt: '2023-05-01',
    profileViews: 65,
    connectionsCount: 22,
    articlesCount: 1,
    menteeCount: 0,
    role: 'user',
  },
  {
    id: 8,
    fullName: 'Dimas Prasetyo',
    email: 'dimas.prasetyo@example.com',
    profilePhoto: '/assets/avatars/avatar-8.png',
    nim: '1201234',
    major: 'Teknik Elektro',
    graduationYear: 2013,
    position: 'Solutions Architect',
    currentCompany: 'Microsoft Indonesia',
    phoneNumber: '+62812345685',
    address: 'Jakarta, Indonesia',
    bio: 'Solutions architect helping enterprises adopt cloud technologies and digital transformation.',
    interests: [
      'Cloud Architecture',
      'Digital Transformation',
      'Enterprise Solutions',
    ],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
    ],
    workExperience: [
      {
        id: '8',
        company: 'Microsoft Indonesia',
        position: 'Solutions Architect',
        startDate: '2020-03-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'Technology',
      },
    ],
    skills: [
      {
        id: '20',
        name: 'Azure',
        category: 'Cloud',
        level: 'expert',
        endorsements: 35,
        verified: true,
      },
      {
        id: '21',
        name: 'Solution Architecture',
        category: 'Architecture',
        level: 'expert',
        endorsements: 28,
        verified: true,
      },
      {
        id: '22',
        name: 'Enterprise Integration',
        category: 'Architecture',
        level: 'advanced',
        endorsements: 22,
        verified: false,
      },
    ],
    certifications: [
      {
        id: '3',
        name: 'Microsoft Certified: Azure Solutions Architect Expert',
        issuer: 'Microsoft',
        issueDate: '2021-09-10',
        expiryDate: '2024-09-10',
        credentialId: 'MS-AZ-304-123',
        credentialUrl: 'https://docs.microsoft.com/en-us/learn/certifications',
      },
    ],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/dimasprasetyo',
        username: 'dimasprasetyo',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: [
        'Cloud Architecture',
        'Enterprise Solutions',
        'Career Growth',
      ],
      maxMentees: 4,
      currentMentees: 3,
      preferredCommunication: ['Video Call', 'In-person'],
      seekingMentorship: false,
    },
    profileCompleteness: 93,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2022-10-01',
    profileViews: 320,
    connectionsCount: 145,
    articlesCount: 15,
    menteeCount: 3,
    role: 'user',
  },
  {
    id: 9,
    fullName: 'Lina Sari Dewi',
    email: 'lina.sari@example.com',
    profilePhoto: '/assets/avatars/avatar-9.png',
    nim: '2001234',
    major: 'Teknik Elektro',
    graduationYear: 2023,
    position: 'Junior Frontend Developer',
    currentCompany: 'Zenius',
    phoneNumber: '+62812345686',
    address: 'Jakarta, Indonesia',
    bio: 'Fresh graduate passionate about frontend development and creating engaging user interfaces.',
    interests: [
      'Frontend Development',
      'React',
      'Web Technologies',
      'Learning',
    ],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'intermediate' },
    ],
    workExperience: [
      {
        id: '9',
        company: 'Zenius',
        position: 'Junior Frontend Developer',
        startDate: '2023-08-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'Education Technology',
      },
    ],
    skills: [
      {
        id: '23',
        name: 'React',
        category: 'Frontend',
        level: 'intermediate',
        endorsements: 5,
        verified: false,
      },
      {
        id: '24',
        name: 'JavaScript',
        category: 'Programming',
        level: 'intermediate',
        endorsements: 8,
        verified: false,
      },
      {
        id: '25',
        name: 'CSS',
        category: 'Frontend',
        level: 'advanced',
        endorsements: 6,
        verified: false,
      },
    ],
    certifications: [],
    socialLinks: [
      {
        platform: 'github',
        url: 'https://github.com/linasari',
        username: 'linasari',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: false,
      mentorshipAreas: [],
      maxMentees: 0,
      currentMentees: 0,
      preferredCommunication: [],
      seekingMentorship: true,
    },
    profileCompleteness: 65,
    verificationStatus: 'pending',
    accountStatus: 'active',
    joinedAt: '2023-08-01',
    profileViews: 35,
    connectionsCount: 12,
    articlesCount: 0,
    menteeCount: 0,
    role: 'user',
  },
  {
    id: 10,
    fullName: 'Agus Setiawan',
    email: 'agus.setiawan@example.com',
    profilePhoto: '/assets/avatars/avatar-10.png',
    nim: '1101234',
    major: 'Teknik Elektro',
    graduationYear: 2012,
    position: 'Technical Lead',
    currentCompany: 'Grab',
    phoneNumber: '+62812345687',
    address: 'Jakarta, Indonesia',
    bio: 'Technical lead with extensive experience in mobile app development and team management.',
    interests: ['Mobile Development', 'Team Leadership', 'Agile Methodologies'],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
    ],
    workExperience: [
      {
        id: '10',
        company: 'Grab',
        position: 'Technical Lead',
        startDate: '2019-01-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'Transportation Technology',
      },
    ],
    skills: [
      {
        id: '26',
        name: 'React Native',
        category: 'Mobile',
        level: 'expert',
        endorsements: 25,
        verified: true,
      },
      {
        id: '27',
        name: 'Team Leadership',
        category: 'Management',
        level: 'expert',
        endorsements: 20,
        verified: true,
      },
      {
        id: '28',
        name: 'Mobile Architecture',
        category: 'Architecture',
        level: 'advanced',
        endorsements: 18,
        verified: false,
      },
    ],
    certifications: [],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/agussetiawan',
        username: 'agussetiawan',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: [
        'Mobile Development',
        'Technical Leadership',
        'Career Growth',
      ],
      maxMentees: 3,
      currentMentees: 2,
      preferredCommunication: ['Video Call', 'Chat'],
      seekingMentorship: false,
    },
    profileCompleteness: 87,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2022-09-01',
    profileViews: 180,
    connectionsCount: 78,
    articlesCount: 7,
    menteeCount: 2,
    role: 'user',
  },
  {
    id: 11,
    fullName: 'Putri Maharani',
    email: 'putri.maharani@example.com',
    profilePhoto: '/assets/avatars/avatar-11.png',
    nim: '1001234',
    major: 'Teknik Elektro',
    graduationYear: 2011,
    position: 'VP of Engineering',
    currentCompany: 'OVO',
    phoneNumber: '+62812345688',
    address: 'Jakarta, Indonesia',
    bio: 'Engineering executive with 10+ years of experience building scalable fintech solutions.',
    interests: [
      'Fintech',
      'Engineering Leadership',
      'Digital Payments',
      'Team Building',
    ],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
    ],
    workExperience: [
      {
        id: '11',
        company: 'OVO',
        position: 'VP of Engineering',
        startDate: '2021-01-01',
        isCurrent: true,
        location: 'Jakarta, Indonesia',
        industry: 'Financial Technology',
      },
    ],
    skills: [
      {
        id: '29',
        name: 'Engineering Leadership',
        category: 'Management',
        level: 'expert',
        endorsements: 40,
        verified: true,
      },
      {
        id: '30',
        name: 'Fintech',
        category: 'Industry',
        level: 'expert',
        endorsements: 35,
        verified: true,
      },
      {
        id: '31',
        name: 'Strategic Planning',
        category: 'Management',
        level: 'expert',
        endorsements: 30,
        verified: true,
      },
    ],
    certifications: [
      {
        id: '4',
        name: 'Certified ScrumMaster',
        issuer: 'Scrum Alliance',
        issueDate: '2019-03-15',
        expiryDate: '2025-03-15',
        credentialId: 'CSM-789456',
        credentialUrl: 'https://www.scrumalliance.org',
      },
    ],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/putrimaharani',
        username: 'putrimaharani',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: [
        'Engineering Leadership',
        'Fintech',
        'Executive Career Path',
      ],
      maxMentees: 5,
      currentMentees: 4,
      preferredCommunication: ['Video Call', 'In-person'],
      seekingMentorship: false,
    },
    profileCompleteness: 98,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2022-08-01',
    profileViews: 450,
    connectionsCount: 234,
    articlesCount: 20,
    menteeCount: 4,
    role: 'user',
  },
  {
    id: 12,
    fullName: 'Hendra Wijaya',
    email: 'hendra.wijaya@example.com',
    profilePhoto: '/assets/avatars/avatar-1.png',
    nim: '0901234',
    major: 'Teknik Elektro',
    graduationYear: 2010,
    position: 'Principal Engineer',
    currentCompany: 'Sea Limited',
    phoneNumber: '+62812345689',
    address: 'Singapore',
    bio: 'Principal engineer specializing in distributed systems and high-scale architecture.',
    interests: [
      'Distributed Systems',
      'System Architecture',
      'Performance Engineering',
    ],
    languages: [
      { name: 'Indonesian', level: 'native' },
      { name: 'English', level: 'advanced' },
      { name: 'Mandarin', level: 'basic' },
    ],
    workExperience: [
      {
        id: '12',
        company: 'Sea Limited',
        position: 'Principal Engineer',
        startDate: '2020-06-01',
        isCurrent: true,
        location: 'Singapore',
        industry: 'Technology',
      },
    ],
    skills: [
      {
        id: '32',
        name: 'Distributed Systems',
        category: 'Architecture',
        level: 'expert',
        endorsements: 45,
        verified: true,
      },
      {
        id: '33',
        name: 'Java',
        category: 'Programming',
        level: 'expert',
        endorsements: 38,
        verified: true,
      },
      {
        id: '34',
        name: 'System Design',
        category: 'Architecture',
        level: 'expert',
        endorsements: 42,
        verified: true,
      },
    ],
    certifications: [],
    socialLinks: [
      {
        platform: 'linkedin',
        url: 'https://linkedin.com/in/hendrawijaya',
        username: 'hendrawijaya',
      },
      {
        platform: 'github',
        url: 'https://github.com/hendrawijaya',
        username: 'hendrawijaya',
      },
    ],
    privacySettings: {
      profileVisibility: 'public',
      contactInfoVisible: true,
      workInfoVisible: true,
      allowMessages: true,
      allowMentorshipRequests: true,
      showInDirectory: true,
    },
    mentorshipInfo: {
      isAvailableAsMentor: true,
      mentorshipAreas: [
        'System Architecture',
        'Distributed Systems',
        'Senior Engineering Career',
      ],
      maxMentees: 4,
      currentMentees: 3,
      preferredCommunication: ['Video Call', 'Chat'],
      seekingMentorship: false,
    },
    profileCompleteness: 91,
    verificationStatus: 'verified',
    accountStatus: 'active',
    joinedAt: '2022-07-01',
    profileViews: 380,
    connectionsCount: 156,
    articlesCount: 18,
    menteeCount: 3,
    role: 'user',
  },
];

export const GRADUATION_YEARS = [
  'Semua Tahun',
  '2023',
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
  '2016',
  '2015',
  '2014',
  '2013',
  '2012',
  '2011',
  '2010',
];

export const LOCATIONS = [
  'Semua Lokasi',
  'Jakarta',
  'Bandung',
  'Surabaya',
  'Yogyakarta',
  'Medan',
  'Singapore',
  'Luar Negeri',
];

export const COMPANIES = [
  'Semua Perusahaan',
  'Google',
  'Tokopedia',
  'Gojek',
  'Shopee',
  'Traveloka',
  'Bukalapak',
  'Microsoft',
  'Grab',
  'OVO',
  'Sea Limited',
  'Zenius',
];
