name: Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '22'

jobs:
  # Job for linting and type checking
  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Check TypeScript types
        run: npm run type-check

      - name: Check code formatting
        run: npm run format:check

  # Job for building all packages
  build:
    name: Build All Packages
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            backend/dist/
            frontend/.next/
            shared/dist/
          retention-days: 1

  # Job for testing individual packages
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build backend
        run: npm run build --workspace=@teuas/backend

      - name: Type check backend
        run: npm run type-check --workspace=@teuas/backend

      - name: Lint backend
        run: npm run lint --workspace=@teuas/backend

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --workspace=@teuas/frontend
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3001
          NEXT_PUBLIC_APP_URL: http://localhost:3000

      - name: Type check frontend
        run: npm run type-check --workspace=@teuas/frontend

      - name: Lint frontend
        run: npm run lint --workspace=@teuas/frontend

  test-shared:
    name: Test Shared Package
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=@teuas/shared

      - name: Type check shared package
        run: npm run type-check --workspace=@teuas/shared

      - name: Lint shared package
        run: npm run lint --workspace=@teuas/shared

  # Summary job that depends on all others
  success:
    name: Build & Lint Success
    runs-on: ubuntu-latest
    needs: [build, test-backend, test-frontend, test-shared]
    if: always()
    
    steps:
      - name: Check all jobs success
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One or more build/lint jobs failed"
          exit 1
      
      - name: All checks passed
        run: |
          echo "🎉 All build and lint checks passed successfully!"
          echo "✅ Linting and type checking completed"
          echo "✅ All packages built successfully"
          echo "✅ Backend checks passed"
          echo "✅ Frontend checks passed"
          echo "✅ Shared package checks passed"