name: Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '22'

jobs:
  # Job for linting and type checking
  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Check TypeScript types
        run: npm run type-check

      - name: Check code formatting
        run: npm run format:check

  # Job for building individual packages in parallel
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: lint-and-typecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build backend
        run: npm run build --workspace=@teuas/backend

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: backend-dist
          path: backend/dist/
          retention-days: 1

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: lint-and-typecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --workspace=@teuas/frontend

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: frontend-dist
          path: frontend/.next/
          retention-days: 1

  build-shared:
    name: Build Shared Package
    runs-on: ubuntu-latest
    needs: lint-and-typecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=@teuas/shared

      - name: Upload shared artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: shared-dist
          path: shared/dist/
          retention-days: 1

  # Combined build job for verification
  build-all:
    name: Build All Packages Together
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend, build-shared]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build

      - name: Upload combined build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts-combined
          path: |
            backend/dist/
            frontend/.next/
            shared/dist/
          retention-days: 7

  # Summary job that depends on all others
  success:
    name: Build & Lint Success
    runs-on: ubuntu-latest
    needs: [build-all]
    if: always()

    steps:
      - name: Check all jobs success
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "❌ One or more build/lint jobs failed"
          echo "Please check the failed jobs above for details"
          exit 1

      - name: All checks passed
        run: |
          echo "🎉 All build and lint checks passed successfully!"
          echo "✅ Linting and type checking completed"
          echo "✅ Backend built successfully"
          echo "✅ Frontend built successfully"
          echo "✅ Shared package built successfully"
          echo "✅ Combined build verification passed"
